#############################################################################
# Makefile for building: emopic03.app/Contents/MacOS/emopic03
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  emopic03.pro
# Template: app
# Command: /Users/dongxueyi/Applications/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile emopic03.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../Applications/5.5/clang_64/lib/QtGui.framework/Headers -I../../Applications/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -IUI -I../../Applications/5.5/clang_64/mkspecs/macx-clang -F/Users/dongxueyi/Applications/5.5/clang_64/lib
QMAKE         = /Users/dongxueyi/Applications/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = emopic031.0.0
DISTDIR = /Users/dongxueyi/Desktop/emopic03/.tmp/emopic031.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/dongxueyi/Applications/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/dongxueyi/Applications/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		camradialog.cpp moc_mainwindow.cpp \
		moc_camradialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		camradialog.o \
		moc_mainwindow.o \
		moc_camradialog.o
DIST          = ../../Applications/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Applications/5.5/clang_64/mkspecs/qdevice.pri \
		../../Applications/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Applications/5.5/clang_64/mkspecs/common/unix.conf \
		../../Applications/5.5/clang_64/mkspecs/common/mac.conf \
		../../Applications/5.5/clang_64/mkspecs/common/macx.conf \
		../../Applications/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Applications/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Applications/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Applications/5.5/clang_64/mkspecs/common/clang.conf \
		../../Applications/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Applications/5.5/clang_64/mkspecs/qconfig.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Applications/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Applications/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Applications/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Applications/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Applications/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Applications/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Applications/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Applications/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Applications/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Applications/5.5/clang_64/mkspecs/features/qt.prf \
		../../Applications/5.5/clang_64/mkspecs/features/resources.prf \
		../../Applications/5.5/clang_64/mkspecs/features/moc.prf \
		../../Applications/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Applications/5.5/clang_64/mkspecs/features/uic.prf \
		../../Applications/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Applications/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Applications/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Applications/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Applications/5.5/clang_64/mkspecs/features/lex.prf \
		emopic03.pro mainwindow.h \
		camradialog.h main.cpp \
		mainwindow.cpp \
		camradialog.cpp
QMAKE_TARGET  = emopic03
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = emopic03.app/Contents/MacOS/emopic03

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): UI/ui_mainwindow.h UI/ui_camradialog.h $(OBJECTS)  
	@test -d emopic03.app/Contents/MacOS/ || mkdir -p emopic03.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: emopic03.pro ../../Applications/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../Applications/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Applications/5.5/clang_64/mkspecs/qdevice.pri \
		../../Applications/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Applications/5.5/clang_64/mkspecs/common/unix.conf \
		../../Applications/5.5/clang_64/mkspecs/common/mac.conf \
		../../Applications/5.5/clang_64/mkspecs/common/macx.conf \
		../../Applications/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Applications/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Applications/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Applications/5.5/clang_64/mkspecs/common/clang.conf \
		../../Applications/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Applications/5.5/clang_64/mkspecs/qconfig.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Applications/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Applications/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Applications/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Applications/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Applications/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Applications/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Applications/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Applications/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Applications/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Applications/5.5/clang_64/mkspecs/features/qt.prf \
		../../Applications/5.5/clang_64/mkspecs/features/resources.prf \
		../../Applications/5.5/clang_64/mkspecs/features/moc.prf \
		../../Applications/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Applications/5.5/clang_64/mkspecs/features/uic.prf \
		../../Applications/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Applications/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Applications/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Applications/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Applications/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Applications/5.5/clang_64/mkspecs/features/lex.prf \
		emopic03.pro \
		/Users/dongxueyi/Applications/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/dongxueyi/Applications/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/dongxueyi/Applications/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile emopic03.pro
../../Applications/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../Applications/5.5/clang_64/mkspecs/qdevice.pri:
../../Applications/5.5/clang_64/mkspecs/features/device_config.prf:
../../Applications/5.5/clang_64/mkspecs/common/unix.conf:
../../Applications/5.5/clang_64/mkspecs/common/mac.conf:
../../Applications/5.5/clang_64/mkspecs/common/macx.conf:
../../Applications/5.5/clang_64/mkspecs/common/sanitize.conf:
../../Applications/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../Applications/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Applications/5.5/clang_64/mkspecs/common/clang.conf:
../../Applications/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../Applications/5.5/clang_64/mkspecs/qconfig.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Applications/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Applications/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../Applications/5.5/clang_64/mkspecs/features/qt_config.prf:
../../Applications/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../Applications/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Applications/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../Applications/5.5/clang_64/mkspecs/features/default_pre.prf:
../../Applications/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../Applications/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../Applications/5.5/clang_64/mkspecs/features/default_post.prf:
../../Applications/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../Applications/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../Applications/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../Applications/5.5/clang_64/mkspecs/features/warn_on.prf:
../../Applications/5.5/clang_64/mkspecs/features/qt.prf:
../../Applications/5.5/clang_64/mkspecs/features/resources.prf:
../../Applications/5.5/clang_64/mkspecs/features/moc.prf:
../../Applications/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../Applications/5.5/clang_64/mkspecs/features/uic.prf:
../../Applications/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../Applications/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../Applications/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../Applications/5.5/clang_64/mkspecs/features/exceptions.prf:
../../Applications/5.5/clang_64/mkspecs/features/yacc.prf:
../../Applications/5.5/clang_64/mkspecs/features/lex.prf:
emopic03.pro:
/Users/dongxueyi/Applications/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/dongxueyi/Applications/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/dongxueyi/Applications/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile emopic03.pro

qmake_all: FORCE

emopic03.app/Contents/PkgInfo: 
	@test -d emopic03.app/Contents || mkdir -p emopic03.app/Contents
	@$(DEL_FILE) emopic03.app/Contents/PkgInfo
	@echo "APPL????" > emopic03.app/Contents/PkgInfo
emopic03.app/Contents/Resources/empty.lproj: 
	@test -d emopic03.app/Contents/Resources || mkdir -p emopic03.app/Contents/Resources
	@touch emopic03.app/Contents/Resources/empty.lproj
	
emopic03.app/Contents/Info.plist: 
	@test -d emopic03.app/Contents || mkdir -p emopic03.app/Contents
	@$(DEL_FILE) emopic03.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,dxy.emopic03,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,emopic03,g" -e "s,@TYPEINFO@,????,g" ../../Applications/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >emopic03.app/Contents/Info.plist

all: Makefile \
		emopic03.app/Contents/PkgInfo \
		emopic03.app/Contents/Resources/empty.lproj \
		emopic03.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h camradialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp camradialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui camradialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r emopic03.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_camradialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_camradialog.cpp
moc_mainwindow.cpp: ../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		mainwindow.h
	/Users/dongxueyi/Applications/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/dongxueyi/Applications/5.5/clang_64/mkspecs/macx-clang -I/Users/dongxueyi/Desktop/emopic03 -I/Users/dongxueyi/Applications/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/dongxueyi/Applications/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/dongxueyi/Applications/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/dongxueyi/Applications/5.5/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_camradialog.cpp: ../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		camradialog.h
	/Users/dongxueyi/Applications/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/dongxueyi/Applications/5.5/clang_64/mkspecs/macx-clang -I/Users/dongxueyi/Desktop/emopic03 -I/Users/dongxueyi/Applications/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/dongxueyi/Applications/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/dongxueyi/Applications/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/dongxueyi/Applications/5.5/clang_64/lib camradialog.h -o moc_camradialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: UI/ui_mainwindow.h UI/ui_camradialog.h
compiler_uic_clean:
	-$(DEL_FILE) UI/ui_mainwindow.h UI/ui_camradialog.h
UI/ui_mainwindow.h: mainwindow.ui
	/Users/dongxueyi/Applications/5.5/clang_64/bin/uic mainwindow.ui -o UI/ui_mainwindow.h

UI/ui_camradialog.h: camradialog.ui
	/Users/dongxueyi/Applications/5.5/clang_64/bin/uic camradialog.ui -o UI/ui_camradialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/QTextCodec \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/qtextcodec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		trackline.h \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Applications/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Applications/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Applications/5.5/clang_64/lib/QtGui.framework/Headers/QFont \
		../../Applications/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Applications/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QFontDialog \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Applications/5.5/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Applications/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

camradialog.o: camradialog.cpp camradialog.h \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Applications/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_camradialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camradialog.o camradialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_camradialog.o: moc_camradialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camradialog.o moc_camradialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

